import Navbar from '@/components/Navbar'
import Session from '@/components/Session'
import '@/styles/globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <Session>
        <body className={`${inter.className} bg-gray-200`}>
          <Navbar />
          <div className='max-w-4xl mx-auto py-6'>
            {children}
          </div>
        </body>
      </Session>
    </html>
  )
}
